---
- hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Create group mandj
      group:
        name: mandj
        gid: 1002
        state: present
        
    - name: Create group gpio
      group:
        name: gpio
        state: present
        system: yes

    - name: Create a user account for Mike
      user:
        name: mike
        uid: 1969
        group: mandj
        password: '$6$ZbWanugns2E$6FeGCSWq97yivD1OZEMPPPWqEzhn.5GbvU4HEe.ohb7lXp3Dz5PcFWggdFh9.d/uvWr9Fbp4XiET2vahDALDY.'
        groups: adm, dialout, cdrom, floppy, sudo, audio, dip, video, plugdev, netdev, gpio
        append: yes
        state: present
        shell: /bin/bash
        system: no
        create_home: yes

    - name: Set Mike's authorized_key for X200
      authorized_key:
        user: mike
        state: present
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIELda1s1OlsuYJK3lrYVLX6fQytK4H9/lNXBlRIrM+aYR0xvMfzYtr2k0JFAaX53PUMuPgIO/qqYK3DjwUtqfeBlYuqVsCvUUxLMfUM4u1sxYHxmI/PVSh02SrwvV4cibCr0ni1SW22j4+k7K34jm1CQeI5e5+ZlcbYL4jThNK8JXwLhOB3/VBdicj+Z66uWAtcPZ67Z7w0wpEnuO5jfTphRoBzL+DeJhYmdipfFOlqaRuzQ/raNwyBqDSy92k01w+vzDnQOSq1nsXE8femzBEmV2Y0M5XxAn50Hbtt5A6oaaLO8xObkaQrmQpEfUsC63jU1z6e7iN7lLQcdp9DCN mike@X200'
      
    - name: Set Mike's authorized_key for PineBookPro
      authorized_key:
        user: mike
        state: present  
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1Qsji4M/UXHerft05HMTfxl1F0GBLaetaaqHvrQkmb2jaZMpIfh0WCYEf2PwZC0kY/2Ex1PQ8R9ZLZHEqkOmJ1ZXcmbwTo0k6Zx4wrNGl7KPWfLPCDTi/zT25ZEe+gZqZgpvF8gdUpyiXEf60mz8uvC54IRjpILEgXxfugpN9qcmW0C3lFcUTFKfXV3ZCjwZ6urL3qdWfyIjKzZ667M1gsyvzxllmBchrPBcnWySGP0SZ8O049Sqa50QoLAaPLeX15w6ELCTVVJEQeQ8mFw0HfPL91ceg3vy1IJuBFOzSA8ZtUM5nZgv+axY3Hx9yU/oTRGJmTQKKVXaqlZqlCKTV rock@Debian-Desktop'

    - name: Set Mike's authorized_key for rpi11
      authorized_key:
        user: mike
        state: present  
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtT6uZEnxcZaI5SoO1m6tip/22Q8Rr+46cPvnIHCokzVBPLwZQQtWSrYj6ethAvT9c86oRv+m3E5IW+EHRpJrBHhYq0ZtKdmRd1xip2+LXaIJeVccIkPImV8oRbxgq53m2zZxnD7Z5BCxGbUqmDgezd8XiUCqGX4Rnu7tngdVwRJGgUFJ1gnBNwd+C0kLkbVRINRY3GUBKeMHmGD6tNkxHy5JLZci66Fw/+lJwr8bPKGNusiNKUDoAjwvTlbFNnrALGp0hMQ3ivfYrUxvV8/v8fxOswV6yocgb7f5QzKpFi7Uy9M+QGBEjbRNfRj8p3XbUnIyq2oDgIMybhu892Rgd pi@rpi11.orchard'

    - name: Set Mike's authorized_key for mobile phone
      authorized_key:
        user: mike
        state: present  
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCu3N2XI9dUvWembGKEpMO5jay9m5i5OYc3YpZ+AHp5ae2+JrAvSbkKo7U2imyzBbcKUI85bJt5jsETuSmc/3K1cR/18VLAVa37mSbUw1KdsXXTSg9fsAUY9+422+QPRMoiMTj23rFARTDIbxG95hlCrHuNWsi9nnqhQ4KuZ87/rLNG91XtIJAODhdhAvWW7uLBHOb0G9I8eKG5kXBiPOvku57TtCxJsl4r1DWjwFZS6g3/DCzPenitvIpxEn3rxcEVtRoMOHcy96rhFdnDUI7zM9t5yXD7RapK8qwYEnUm2d2WAS7WR5iAQYswOiWaXGhiEfD42oONLT73WPmQ24stW30Hw+XxEJRxCBXWWfVU7GO1+BKxGL+U9L/CD0qbzGKKmsf6Jy4LEikc1jmBdv0jsrSSZlQXyQgePGxwoo4Qv/Dv0VPuZ3Bx6SyPzdYj1DIjqz7CZKTlDAGpnfOqaYz/1MLjn2wTw3CijUiXgTH8N7MN7mPM9/5hnyTyw1U3EDc= u0_a78@localhost'

    - name: Set Mike's authorized_key for wsl
      authorized_key:
        user: mike
        state: present  
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYS3GwNSZhDav8e90goZU1lJKFh1wJ77Rxn5qiXyMZpO+Y1ZX+NhzBLZjgvct8uxpq8weTy9l3bMgHhm8dcdT6mH/E7kPFphCfKugtvJGm/NUqP2g/KdEngpDlymi3bAOOmShLolkwnzAji0+KlRqu13dlZAmjZr8erNsunQu3MqtpdlOhhNi2O1ybiiiHThSFR0DPYx+n27pimCS37DELdClKDc2f9yofnk80NXXwzbmrX/vgOiuPW69rWhFsVJK72q4AXN5PvlK9hNiAr3gy3s/SfP1dNrqw0410YVHJH4C3SCWSAt3MOVbVoMskOMpzJiZQaI8ByjpuXJ/2zXK3 mike@WS-007879'

    - name: Set hostname
      hostname:
        name: garage.orchard
    - name: Ensure hosts file has correct hostname too
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: 127.0.1.1       garage.orchard
     
    - name: "Change SSH port number"
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 7056"
      notify: Restart ssh
      
    - name: Disallow password authentication
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Restart ssh
  
    - name: Set timezone
      timezone:
        name: Europe/London

    - name: Set GB locale
      locale_gen:
        name: en_GB.UTF-8
        state: present
        
#    - name: Delete user account 'ubuntu'
#      user:
#        name: ubuntu
#        state: absent
#        remove: yes
#        force: yes
        
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds (1 hr) ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Install packages
      apt:
        pkg:
        - python3
        - python3-gpiozero
        - tmux
        - vim
        - mariadb-server
        - mariadb-client
        - python3-mysqldb
        
#    - name: Reboot the machine
#      reboot:

    - name: Adjust RPi settings in /boot/config.txt
      lineinfile:
        path: /boot/config.txt
        line: dtoverlay=w1-gpio
        
  handlers:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
