---
- hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Change password of user 'ubuntu'
      user:
        name: ubuntu
        password: '$6$ZbWanugns2E$6FeGCSWq97yivD1OZEMPPPWqEzhn.5GbvU4HEe.ohb7lXp3Dz5PcFWggdFh9.d/uvWr9Fbp4XiET2vahDALDY.'
        
    - name: "Set authorized_key for ubuntu"
      authorized_key:
        user: ubuntu
        state: present
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfkrYk+p/FqFKPPf1nkGz/Xm5cLyV6GBXImyMiTV0jngH83FutCfrI65eFZiYCu4eeXbdexSZho2m7gJndamx8/iQodJHT8hYMXPAhTsISmrUvQ3h6U65zoENnP0OFXibHS8JLSbdded3c9TiDBmwWTLm2SkcW/eH2LbpJTIEFuy7i6cgBvE4rp/WmyzNQlV8x47kqqGPuuBs0hQkHK022hA3QE2yubQcIYvpaAvhWWvvddWTQAYA0MhzAmbXT1kWUrKpUvcQjWiGRV2UI3y7MXHBzwzqclAxkuz7/VB9BHlsR0H204gWaSA+gIgBuZqwvmaqeHGAFiD8HZD1T0U0F mike@ac-l08'
