---
- hosts: localhost
  connection: local
  become: yes
  vars:
    host_name: oracle2.strangerthandata.com
  
  tasks:
    - name: Create group mandj
      group:
        name: mandj
        gid: 1002
        state: present
        
    - name: Create group docker
      group:
        name: docker
        state: present
        
    - name: Create a user account for Mike
      user:
        name: mike
        uid: 1969
        group: mandj
        password: '$6$ZbWanugns2E$6FeGCSWq97yivD1OZEMPPPWqEzhn.5GbvU4HEe.ohb7lXp3Dz5PcFWggdFh9.d/uvWr9Fbp4XiET2vahDALDY.'
        groups: adm, dialout, cdrom, sudo, audio, video, plugdev, games, users, input, netdev, docker
        append: yes
        state: present
        shell: /bin/bash
        system: no
        create_home: yes

    - name: Set Mike's authorized_key for P14s
      authorized_key:
        user: mike
        state: present  
        key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJCtzjhKZSmZ4gvmUZlCCQxMmfg/6KEf7qSmEBFyT2wt mike@ThinkPad-P14s-Gen-2a'
      
    - name: Set Mike's authorized_key for server
      authorized_key:
        user: mike
        state: present
        key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7tew3lbJkHS5LCC1Ad/sdfz1mWQXxCAbiYULZhazJ9 mike@apple'
        
    - name: Set hostname
      hostname:
        name: "{{ host_name }}"
    - name: Ensure hosts file has correct hostname too
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: 127.0.1.1       {{ host_name }}
     
    - name: "Change SSH port number"
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 22"
      notify: Restart ssh
      
    - name: Disallow password authentication
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Restart ssh
  
    - name: Set timezone
      timezone:
        name: Europe/London
        
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds (1 hr) ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Install packages
      apt:
        pkg:
        - tree
        - python3
        - python3-pip
        - python3-matplotlib
        - tmux
        - vim
        - mariadb-server
        - mariadb-client
        - python3-mysqldb
        - nmap
        - arp-scan
        - mtr
        - whois
        - mc
        - htop
        - ncdu
        - neofetch
        - screenfetch
        - inxi
        - mutt
        - magic-wormhole
        - sshguard
        - python3-apt
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - ufw
        - wavemon
        - cmake
        - locales
        
    - name: Set GB locale
      locale_gen:
        name: en_GB.UTF-8
        state: present

    - name: Create scripts subdirectory
      file:
        path: /home/mike/scripts
        state: directory
        mode: '0755'
        owner: mike
        group: mandj

    - name: Download reboot check script
      get_url:
        url: https://raw.githubusercontent.com/Bicko/vps-provisioning/master/is-reboot-required.sh
        dest: /home/mike/scripts/is-reboot-required.sh
        mode: '0755'
        owner: mike
        group: mandj

    - name: Create tmux config file
      copy:
        dest: /home/mike/.tmux.conf
        content: |
          set -g status-bg blue
          set -g status-fg white
          set -ga message-style bg=yellow
          set -g message-style fg=black
          set -g pane-border-style fg=blue
          set -g pane-active-border-style fg=red
        backup: yes
        mode: '0644'
        owner: mike
        group: mandj

    - name: Configure Firewall
      command: "ufw {{ item }}"
      with_items:
        #- --force reset
        - default deny incoming
        - default allow outgoing
        - allow 22/tcp
        - --force enable
    - name: Stop UFW logging to /var/log/syslog
      lineinfile:
        path: /etc/rsyslog.d/20-ufw.conf
        regexp: ' *# *& *stop *'
        line: '& stop'

    #- name: Add Docker’s official GPG key
    #  apt_key:
    #    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    #    url: https://download.docker.com/linux/ubuntu/gpg
    #    state: present
        
    #- name: Add Docker repository into sources list.
    #  apt_repository:
    #    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    #    state: present
    #    mode: '0644'
        
    #- name: Update apt
    #  apt:
    #    update_cache: yes
    #    force_apt_get: yes
        
    #- name: Install Docker
    #  apt:
    #    pkg:
    #    - docker-ce
    #    - docker-ce-cli
    #    - containerd.io
    #    - haveged
        
    #- name: Download docker-compose
    #  get_url:
    #    url: https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    #    dest: /usr/local/bin/docker-compose
    #    mode: '0755'

    #- name: apt-get upgrade
    #  apt:
    #    upgrade: dist
    #    force_apt_get: yes
        
    - name: apt-get autoremove
      apt:
        autoremove: yes

  handlers:
    - name: Restart ssh
      service:
        name: sshd
        state: restarted
